project:
  type: website
  output-dir: docs
  
website:
  title: "Dillon Sparks"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - why.qmd
      - projects.qmd
      - personal_projects.qmd
    tools:
      - icon: github
        menu:
          - text: LinkedIn
            url:  https://www.linkedin.com/in/dillonsparks1/

format:
  html:
    theme: sketchy
    toc: true

editor: source

