---
title: "Projects"
about: 
  id: alma
  template: solana
  links: 
    - icon: share
      text: NYC DOE Student Demographics Project
      href: https://dillonsparks.github.io/education/
    - icon: share
      text: Columbia DSI Scholars Project
      href: https://datascience.columbia.edu/research/columbia-dsi-scholars/
    - icon: share
      text: UseRinfoboard dashboard
      href: https://rconf.gitlab.io/userinfoboard/
---

## NYC DOE Student Demographics Project

This was a final project that I originally completed for my Exploratory Data Analysis and Visualization course during my first semester at Columbia. This project was intended to explore the intersections of race/ethnicity, disability status, income, and English language learner status with NYC public elementary and middle school standardized test scores. Feel free to find the entire process and analyses [here](https://dillonsparks.github.io/education/). 




## Columbia DSI Scholars Project
DSI Scholars & SEED data 

This project was the end result of my time as a Project Data Analyst for Columbia University's Data Science Institute. I met with program leadership at the start of the project and by the end of the meeting their goal was simple: to visualize the DSI's reach and influence across the various schools at Columbia, through the DSI Scholars program. The data cleaning process for this role was *extensive*, and often very manual at times. As a result, I developed a different data collection process for program leadership that would facilitate future analysis and visualization, significantly cutting down on the amount of wrangling future data. A more detailed description of the DSI Scholars program and the final visualization can be found [here](https://datascience.columbia.edu/research/columbia-dsi-scholars/). 


## UseRinfoboard Dashboard

My most recent (and ongoing) role is working as a Data Analyst for the [R Forwards Taskforce for women and other underrepresented groups](https://forwards.github.io/). My responsibilities here include reorganizing and cleaning data from previous conferences, updating the public dashboard to showcase the conference's impact on the larger R community, contirbuting to final reports and analysis of conferences, and writing code to facilitate the integration of future data to the dashboard. The developing dashboard can be found [here](https://rconf.gitlab.io/userinfoboard/) and my specific contributions can be found here on my [GitLab profile](https://gitlab.com/dms327). 

```{r, echo=FALSE}
## Project 4
# need a project where I build and end to end pipeline/model ** 
```

