---
title: "My why"
---

My high school made a concerted effort to provide students with enrichment opportunities in hopes of increasing college enrollment. However, these opportunities were not accessible to most students because I went to an underfunded, majority Black, public school in Harlem, New York. With such limited room for error, only students deemed respectable in the eyes of donors were chosen to represent the school. I was a straight “A” student who made an intentional effort to build good rapport with all of my teachers, and thus, I had access to everything my school had to offer. Consequently, I internalized harmful ideas of respectability and deservingness. 

Inevitably, these beliefs came into question during my sophomore year of college when I was introduced to higher level math courses. No amount of hard work or office hour attendance was sufficient for me to succeed. As one of the few remaining Black math majors in my class, I truly wondered if I even deserved to be at Georgetown.  

The lowest point in my academic career forced me to opt out of the false dichotomy of those who deserved access to higher education and those who did not. Not only was I confronted with the challenges of navigating a rigorous STEM curriculum in college, but also tasked with seeking out and developing a sense of community in a major that historically pushes out Black students. I shifted my attention towards building community with other Black and Brown STEM students instead of questioning whether I belonged. My confidence flourished and I grew more comfortable with asking questions, taking risks, and pursuing leadership roles within the Math department. 

Furthermore, I began to study educational equity, the school-to-prison pipeline, and other relevant phenomena through my work at Georgetown’s Center for Social Justice (CSJ). I found statistical evidence explaining why I was one of few underrepresented minorities in all my math classes. This work fueled my interest in a quantitatively-focused career because it was the first time that numbers and data furthered my own understanding of my lived experiences. Prior to this discovery, I felt obligated to separate my love for math from my interest in social justice. A degree in math felt like an ultimatum between what I loved to do and investing in my community. Now, I consider both to be integral parts of my academic and career goals. 

I recently received my Master’s in Data Science from Columbia University, where I gained the requisite skills and experience to succeed as a data scientist. Oftentimes, perseverance alone is insufficient to overcome the systemic barriers that historically marginalized groups face in everyday life. I will use data science to provide evidence of the need for more equitable systems, creating the community and opportunities that everyone deserves for the inevitable times when hard work falls short of being recognized. 
